### ISSUE TITLE
Mismatch in install of share/models

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/teo-grasp#2]
Mismatch in install of `share/models`:
- `teo-grasp` is defined as project, [here](https://github.com/roboticslab-uc3m/teo-grasp/blob/8683e57903817cdc7452213ba7312c104815b4e0/share/CMakeLists.txt#L8)
- `grasp` is used as path, [here](https://github.com/roboticslab-uc3m/teo-grasp/blob/8683e57903817cdc7452213ba7312c104815b4e0/share/models/CMakeLists.txt#L9)

**Comment by rsantos88** [comment]
solved it (b8bd40bf0442faaaf454882b5c12f4305f88efbf)
Thanks @jgvictores

**Comment by jgvictores** [comment]
b8bd40bf0442faaaf454882b5c12f4305f88efbf was pretty hard-coded... Good example:
- `teo-openrave-models` https://github.com/roboticslab-uc3m/teo-openrave-models/blob/develop/openrave/CMakeLists.txt#L11
- `TEO-OPENRAVE-MODELS_CONTEXTS_INSTALL_DIR` https://github.com/roboticslab-uc3m/teo-openrave-models/blob/develop/openrave/CMakeLists.txt#L18

Note the unfortunate mix of kebab-case and SCREAMING_SNAKE_CASE, documented as best as possible as stated https://github.com/roboticslab-uc3m/best-practices/issues/5#issuecomment-345614754

**Comment by rsantos88** [comment]
> b8bd40b was pretty hard-coded... 

solved it (492dd2dcb74605a39d9ee37b859075e83023da37)

**Comment by jgvictores** [comment]
That looks much better!!!

Thanks!

**Comment by jgvictores** [comment]
Ok, sorry to bug on this issue, there are now duplicates:
1. https://github.com/roboticslab-uc3m/teo-grasp/blob/492dd2dcb74605a39d9ee37b859075e83023da37/share/CMakeLists.txt#L8
1. https://github.com/roboticslab-uc3m/teo-grasp/blob/492dd2dcb74605a39d9ee37b859075e83023da37/share/models/CMakeLists.txt#L9

I'd remove the second one, which should not be required.

**Comment by rsantos88** [comment]
@jgvictores don't worry, it's ok.
I've removed the second one :+1:  (c3f4af41e143b0d4fdf0fdad42e40bae86c67b63)
If you see something wrong, tell me.

**Comment by jgvictores** [comment]
Commited a26a55e898ee23ab2f492d481ed96427784a6626 :-)

**Comment by jgvictores** [comment]
PS: Much more info on this here: http://www.yarp.it/yarp_external_build.html

**Comment by jgvictores** [comment]
Also commited: 1aa055c0e2dd6de11df1c2e810c6d7b52c83274a

**Comment by PeterBowman** [comment]
If you want to read axis-angle data, launch the server device with `--angleRepr axisAngle`. Similarly, start the client device with `--transform` to connect it with `/portname/rpc_transform:s` (instead of the usual `/portname/rpc:s`, which falls back to standard KDL twist representation, that is, 3xtranslation + 3xrotation in scaled axis-angle notation).

Please read roboticslab-uc3m/kinematics-dynamics/issues/113.

> It works well but we don't know the units (degrees or radians?)

There was a major documentation overhaul several months ago, check http://robots.uc3m.es/dox-kinematics-dynamics/.
